import asyncio
from collections.abc import AsyncIterator

from app.core.ai import create_ai_provider
from app.core.intent import ZoyaIntentRouter
from app.memory.extractor import MemoryExtractor
from app.memory.manager import MemoryManager


class ZoyaChatService:
    """
    Shared Zoya chat service for web/API interfaces.

    Handles:
    - persistent users
    - conversations
    - long-term memory extraction
    - recent conversation context
    - deterministic intent routing
    - AI provider failover
    - assistant message persistence
    """

    def __init__(self) -> None:
        self.ai = create_ai_provider()
        self.memory = MemoryManager()
        self.extractor = MemoryExtractor()
        self.intent_router = ZoyaIntentRouter()

        # Development-only active conversation mapping.
        # Later this can move fully to DB/auth/session storage.
        self.active_sessions: dict[int, int] = {}

    def _prepare_chat_context(
        self,
        user_id: int,
        user_name: str,
        message: str,
        conversation_id: int | None = None,
    ) -> tuple[
        int,
        str,
        list[dict[str, str]],
        str | None,
    ]:
        """
        Prepare the user, conversation, memory, structured
        history, and deterministic intent routing.

        Returns:
            (
                conversation_id,
                current AI message,
                conversation_history,
                direct_response,
            )
        """
        message = message.strip()

        if not message:
            raise ValueError(
                "Message cannot be empty."
            )

        self.memory.get_or_create_user(
            user_id=user_id,
            name=user_name,
        )

        if conversation_id is None:
            conversation_id = self.active_sessions.get(
                user_id
            )

        if conversation_id is None:
            conversation = self.memory.create_conversation(
                user_id=user_id,
            )

            conversation_id = (
                conversation.conversation_id
            )

            self.active_sessions[user_id] = (
                conversation_id
            )

        # Read previous messages BEFORE saving the
        # current message so the current message is not
        # duplicated in the context.
        recent_messages = self.memory.get_recent_messages(
            conversation_id=conversation_id,
            limit=10,
        )

        conversation_history = [
            {
                "role": item.role,
                "content": item.content,
            }
            for item in recent_messages
            if item.role in {"user", "assistant"}
        ]

        # Deterministic intent routing happens before the
        # AI provider is called.
        intent_decision = self.intent_router.classify(
            message=message,
            conversation_history=conversation_history,
        )

        # Save the current user message regardless of whether
        # the response is generated by the router or provider.
        self.memory.save_message(
            conversation_id=conversation_id,
            user_id=user_id,
            role="user",
            content=message,
        )

        # Extract long-term memories from the current message.
        extracted_memories = self.extractor.extract(
            message
        )

        for item in extracted_memories:
            self.memory.save_memory(
                user_id=user_id,
                category=item["category"],
                key=item["key"],
                value=item["value"],
                importance=item["importance"],
                confidence=item["confidence"],
                source=item["source"],
            )

        # If a high-confidence intent was handled by the
        # deterministic router, no LLM call is needed.
        if intent_decision.handled:
            return (
                conversation_id,
                message,
                conversation_history,
                intent_decision.response,
            )

        # Otherwise load persistent memories for the AI.
        stored_memories = self.memory.get_memories(
            user_id=user_id,
            min_importance=1,
        )

        memory_lines = [
            f"- {item.key}: {item.value}"
            for item in stored_memories
        ]

        memory_context = (
            "\n".join(memory_lines)
            if memory_lines
            else "(No stored memories.)"
        )

        contextual_message = (
            "Persistent memories about Ayan:\n"
            f"{memory_context}\n\n"
            "Current request from Ayan:\n"
            f"{message}"
        )

        return (
            conversation_id,
            contextual_message,
            conversation_history,
            None,
        )

    async def chat(
        self,
        user_id: int,
        user_name: str,
        message: str,
        conversation_id: int | None = None,
    ) -> dict:
        """
        Standard non-streaming chat.

        Kept for existing Discord/API compatibility.
        """
        (
            conversation_id,
            ai_message,
            conversation_history,
            direct_response,
        ) = self._prepare_chat_context(
            user_id=user_id,
            user_name=user_name,
            message=message,
            conversation_id=conversation_id,
        )

        if direct_response is not None:
            reply = direct_response

        else:
            reply = await asyncio.to_thread(
                self.ai.send_message,
                ai_message,
                conversation_history,
            )

        self.memory.save_message(
            conversation_id=conversation_id,
            user_id=user_id,
            role="assistant",
            content=reply,
        )

        return {
            "response": reply,
            "conversation_id": conversation_id,
            "active_provider": (
                "intent-router"
                if direct_response is not None
                else self.ai.active_provider
            ),
        }

    async def stream_chat(
        self,
        user_id: int,
        user_name: str,
        message: str,
        conversation_id: int | None = None,
    ) -> AsyncIterator[str]:
        """
        Stream Zoya's response chunk-by-chunk.

        Deterministic intent-router responses are emitted
        directly without contacting an AI provider.
        """
        (
            conversation_id,
            ai_message,
            conversation_history,
            direct_response,
        ) = self._prepare_chat_context(
            user_id=user_id,
            user_name=user_name,
            message=message,
            conversation_id=conversation_id,
        )

        # ---------------------------------------------------------
        # Deterministic response path
        # ---------------------------------------------------------
        if direct_response is not None:
            self.memory.save_message(
                conversation_id=conversation_id,
                user_id=user_id,
                role="assistant",
                content=direct_response,
            )

            yield direct_response
            return

        # ---------------------------------------------------------
        # AI provider streaming path
        # ---------------------------------------------------------
        loop = asyncio.get_running_loop()

        queue: asyncio.Queue[
            str | Exception | None
        ] = asyncio.Queue()

        def produce() -> None:
            try:
                for chunk in self.ai.stream_message(
                    ai_message,
                    conversation_history,
                ):
                    asyncio.run_coroutine_threadsafe(
                        queue.put(chunk),
                        loop,
                    ).result()

                asyncio.run_coroutine_threadsafe(
                    queue.put(None),
                    loop,
                ).result()

            except Exception as error:
                asyncio.run_coroutine_threadsafe(
                    queue.put(error),
                    loop,
                ).result()

        producer_task = asyncio.create_task(
            asyncio.to_thread(produce)
        )

        chunks: list[str] = []

        try:
            while True:
                item = await queue.get()

                if item is None:
                    break

                if isinstance(item, Exception):
                    raise item

                chunks.append(item)
                yield item

        finally:
            await producer_task

        reply = "".join(chunks).strip()

        if not reply:
            raise RuntimeError(
                "Zoya returned an empty streamed response."
            )

        self.memory.save_message(
            conversation_id=conversation_id,
            user_id=user_id,
            role="assistant",
            content=reply,
        )

    def get_active_conversation_id(
        self,
        user_id: int,
    ) -> int | None:
        """Return the development-only active conversation ID."""
        return self.active_sessions.get(user_id)

    def get_conversation_history(
        self,
        user_id: int,
        conversation_id: int | None = None,
        limit: int = 100,
    ) -> dict:
        """
        Return messages from the active conversation.

        This is used by the web frontend to restore chat history
        after a browser refresh.
        """
        if conversation_id is None:
            conversation_id = self.active_sessions.get(
                user_id
            )

        if conversation_id is None:
            return {
                "conversation_id": None,
                "messages": [],
            }

        messages = self.memory.get_recent_messages(
            conversation_id=conversation_id,
            limit=limit,
        )

        history = [
            {
                "role": item.role,
                "content": item.content,
            }
            for item in messages
            if item.role in {"user", "assistant"}
        ]

        return {
            "conversation_id": conversation_id,
            "messages": history,
        }